# Generated by Django 4.2.17 on 2024-12-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='catuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='catuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='catuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Membro de equipe?'),
        ),
        migrations.AlterField(
            model_name='catuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sobrenome'),
        ),
    ]
