# Generated by Django 4.2.17 on 2024-12-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration_in_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
