# Generated by Django 4.2.17 on 2024-12-20 00:38

import apps.streaming.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_audio_duration_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='cover',
            field=models.FileField(upload_to=apps.streaming.utils.upload_to_instance_folder),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to=apps.streaming.utils.upload_to_instance_folder),
        ),
    ]
