# Generated by Django 4.2.17 on 2024-12-20 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_audio_cover_alter_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
