# Generated by Django 4.2.17 on 2024-12-20 01:02

import apps.streaming.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_audio_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='cover',
            field=models.FileField(blank=True, default=None, null=True, upload_to=apps.streaming.utils.upload_to_instance_folder),
        ),
    ]
