# Generated by Django 4.2.17 on 2024-12-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_audio_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='md5',
            field=models.CharField(default=None, editable=False, max_length=32),
        ),
    ]
