# Generated by Django 4.2.17 on 2024-12-22 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_alter_playlist_audios'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
