# Generated by Django 4.2.17 on 2024-12-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_downloadrequest_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
