# Generated by Django 4.2.17 on 2024-12-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_adminrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('done', 'Finalizado'), ('error', 'Erro'), ('in_process', 'Em Processo')], default='pending', max_length=255),
        ),
    ]
