# Generated by Django 4.2.17 on 2024-12-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_alter_adminrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='genres',
            field=models.ManyToManyField(blank=True, to='streaming.genre'),
        ),
    ]
